spring:
  datasource:
    druid:
      url: jdbc:h2:file:/Users/chenruifeng/Temp/phoenix-wings
      username: sa
      password:
  jpa:
    hibernate.ddl-auto: update
    hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
